# Generated by Django 4.0.2 on 2022-08-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_structure', models.FileField(null=True, upload_to='excel')),
                ('total_cost_to_company', models.PositiveIntegerField(default=20)),
            ],
        ),
    ]
